---
author: "David Dobrowski"
date: "10/21/2019"
output: pdf_document
always_allow_html: yes
params: 
    set_title: "My Title"
    school: "Roosevelt"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)

library(tidyverse)
library(here)
library(scales)
library(knitr)
library(kableExtra)

round2 = function(x, digits) {
  posneg = sign(x)
  z = abs(x)*10^digits
  z = z + 0.5
  z = trunc(z)
  z = z/10^digits
  z*posneg
}



sbac.all <- read_rds(here("data", "sbac-all.rds"))

tables <- sbac.all %>%
    filter(`Demographic ID` == "001") %>% 
    mutate(ThreeYrChange = `Percentage Standard Met and Above.19` - `Percentage Standard Met and Above.16` ,
           cds = paste0(`County Code`,`District Code`,`School Code`)) %>%
    select(cds,
           `District Name`,
           `School Name`,
           Grade,
           TestID,
           `Percentage Standard Met and Above.15`,
           `Percentage Standard Met and Above.16`,
           `Percentage Standard Met and Above.17`,
           `Percentage Standard Met and Above.18`,
           `Percentage Standard Met and Above.19`,
           OneYrChange,
           ThreeYrChange)

```





```{r cars, include=FALSE}

sbac.all %>%
    filter(str_detect(`School Name`, params$school),
           `Demographic ID` == "001",
           TestID == "Math") %>% 
    mutate(ThreeYrChange = `Percentage Standard Met and Above.19` - `Percentage Standard Met and Above.16` ) %>%
    select(`District Name`,
           `School Name`,
           Grade,
           `Percentage Standard Met and Above.15`,
           `Percentage Standard Met and Above.16`,
           `Percentage Standard Met and Above.17`,
           `Percentage Standard Met and Above.18`,
           `Percentage Standard Met and Above.19`,
           OneYrChange,
           ThreeYrChange) %>%
    kable(# format = "latex",
          booktabs = T,
        #  escape = FALSE,
        #  caption = .$`School Name`[1],
          col.names = linebreak(c("District",
                        "School",
                        "Grade",
                        "2015",
                        "2016",
                        "2017",
                        "2018",
                        "2019",
                        "1 Year",
                        "3 Years"))
          )  %>% 
    add_header_above(c(" " = 3, "Percent Met or Exceeded" = 5, "Change" = 2)) # %>% 
 #   kable_styling(latex_options = "striped",
               #   full_width = TRUE
  #                ) # %>% 
   # landscape()


```

\newpage



```{r trucks, results='asis',}

cds_list <-unique(tables$cds)#[10:15]

for(i in cds_list){


tbls_step <- tables %>%
    filter(str_detect(cds, i)) %>% 
    select(-cds) 

titl <- paste0(tbls_step[1,1]," - ", tbls_step[1,2])

tbls_math <- tbls_step %>%
  select(-`District Name`, -`School Name`) %>%
  filter(TestID == "Math") %>%
    kable(# format = "latex",
          booktabs = T,
        #  escape = FALSE,
           caption = paste0(titl," - Math"),    # "For ", .$`School Name`[1]),
          col.names = (c(
                        "Grade",
                        "Test",
                        "2015",
                        "2016",
                        "2017",
                        "2018",
                        "2019",
                        "1 Year",
                        "3 Years"))
          )  %>% 
    add_header_above(c(" " = 2, "Percent Met or Exceeded" = 5, "Change" = 2)) # %>% 
 #   kable_styling(latex_options = "striped",
               #   full_width = TRUE
  #                ) # %>% 
   # landscape()

tbls_ela <- tbls_step %>%
  select(-`District Name`, -`School Name`) %>%
  filter(TestID == "ELA") %>%
    kable(# format = "latex",
          booktabs = T,
        #  escape = FALSE,
           caption = paste0(titl," - ELA"),    # "For ", .$`School Name`[1]),
          col.names = (c(
                        "Grade",
                        "Test",
                        "2015",
                        "2016",
                        "2017",
                        "2018",
                        "2019",
                        "1 Year",
                        "3 Years"))
          )  %>% 
    add_header_above(c(" " = 2, "Percent Met or Exceeded" = 5, "Change" = 2)) # %>% 


cat("  \n")
cat("  \n")


print("*Based on https://caaspp-elpac.cde.ca.gov/caaspp/")


cat("  \n")
cat("  \n")


print(tbls_ela)

cat("  \n")


print(tbls_math)


cat("  \n")

cat('\\pagebreak')

}

```



